<p><blockquote><h1>지필평가 교과목별 정답/배점</h1></blockquote></p><p>고사: 기말고사  교과목 : 국어</p>
<table>
    <thead>
    <tr>
        <th>문항</th>
        <th>배점</th>
        <th>정답</th>
        <th>복수구분</th>
        <th>문항</th>
        <th>배점</th>
        <th>정답</th>
        <th>복수구분</th>
        <th>문항</th>
        <th>배점</th>
        <th>정답</th>
        <th>복수구분</th>
        <th>문항</th>
        <th>배점</th>
        <th>정답</th>
        <th>복수구분</th>
    </tr>
    <tr>
        <th>1</th>
        <th>3</th>
        <th>4</th>
        <th></th>
        <th>16</th>
        <th>4</th>
        <th>3</th>
        <th></th>
        <th>31</th>
        <th></th>
        <th></th>
        <th></th>
        <th>46</th>
        <th></th>
        <th></th>
    </tr>
    
    <tr>
        <th>2</th>
        <th>4</th>
        <th>5</th>
        <th></th>
        <th>17</th>
        <th>4</th>
        <th>1</th>
        <th></th>
        <th>32</th>
        <th></th>
        <th></th>
        <th></th>
        <th>47</th>
        <th></th>
        <th></th>
    </tr>

    <tr>
        <th>3</th>
        <th>3</th>
        <th>2</th>
        <th></th>
        <th>18</th>
        <th>4</th>
        <th>5</th>
        <th></th>
        <th>33</th>
        <th></th>
        <th></th>
        <th></th>
        <th>48</th>
        <th></th>
        <th></th>
    </tr>
    
    <tr>  
        <th>4</th>
        <th>3</th>
        <th>5</th>
        <th></th>
        <th>19</th>
        <th>4</th>
        <th>2</th>
        <th></th>
        <th>34</th>
        <th></th>
        <th></th>
        <th></th>
        <th>49</th>
        <th></th>
    </tr>
        <tr>
            <th>5</th>
            <th>2</th>
            <th>4</th>
            <th></th>
            <th>20</th>
            <th></th>
            <th></th>
            <th></th>
            <th>35</th>
            <th></th>
            <th></th>
            <th></th>
            <th>50</th>
            <th></th>
            <th></th>
        </tr>
        <tr>
            <th>6</th>
            <th>4</th>
            <th>2</th>
            <th></th>
            <th>21</th>
            <th></th>
            <th></th>
            <th></th>
            <th>36</th>
            <th></th>
            <th></th>
            <th></th>
            <th>51</th>
            <th></th>
            <th></th>
        </tr>
        <tr>        
            <th>7</th>
            <th>4</th>
            <th>3</th>
            <th></th>
            <th>22</th>
            <th></th>
            <th></th>
            <th></th>
            <th>37</th>
            <th></th>
            <th></th>
            <th></th>
            <th>52</th>
            <th></th>
        </tr>
        <tr> 
            <th>8</th>
            <th>4</th>
            <th>3</th>
            <th></th>
            <th>23</th>
            <th></th>
            <th></th>
            <th></th>
            <th>38</th>
            <th></th>
            <th></th>
            <th></th>
            <th>53</th>
            <th></th>
        </tr>
        <tr> 
            <th>9</th>
            <th>3</th>
            <th>5</th>
            <th></th>
            <th>24</th>
            <th></th>
            <th></th>
            <th></th>
            <th>39</th>
            <th></th>
            <th></th>
            <th></th>
            <th>54</th>
            <th></th>
        </tr>
        <tr> 
            <th>10</th>
            <th>4</th>
            <th>3</th>
            <th></th>
            <th>25</th>
            <th></th>
            <th></th>
            <th></th>
            <th>40</th>
            <th></th>
            <th></th>
            <th></th>
            <th>55</th>
            <th></th>
        </tr>
        <tr> 
            <th>11</th>
            <th>4</th>
            <th>3</th>
            <th></th>
            <th>26</th>
            <th></th>
            <th></th>
            <th></th>
            <th>41</th>
            <th></th>
            <th></th>
            <th></th>
            <th>56</th>
            <th></th>
        </tr>
        <tr> 
            <th>12</th>
            <th>4</th>
            <th>5</th>
            <th></th>
            <th>27</th>
            <th></th>
            <th></th>
            <th></th>
            <th>42</th>
            <th></th>
            <th></th>
            <th></th>
            <th>57</th>
            <th></th>
        </tr>
        <tr> 
            <th>13</th>
            <th>4</th>
            <th>1</th>
            <th></th>
            <th>28</th>
            <th></th>
            <th></th>
            <th></th>
            <th>43</th>
            <th></th>
            <th></th>
            <th></th>
            <th>58</th>
            <th></th>
        </tr>
        <tr> 
            <th>14</th>
            <th>4</th>
            <th>3</th>
            <th></th>
            <th>29</th>
            <th></th>
            <th></th>
            <th></th>
            <th>44</th>
            <th></th>
            <th></th>
            <th></th>
            <th>59</th>
            <th></th>
        </tr>
        <tr> 
            <th>15</th>
            <th>4</th>
            <th>4</th>
            <th></th>
            <th>30</th>
            <th></th>
            <th></th>
            <th></th>
            <th>45</th>
            <th></th>
            <th></th>
            <th></th>
            <th>60</th>
            <th></th>
        </tr>
    </thead>
    
</table>
